channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.1
  - pip
  - pip:
      - azureml-defaults
      - azureml-mlflow
      - ray-on-aml
      - torch
      - torchvision
name: azureml_cfc9e96c7b0b43301a0ba4c6bd3548e5
