channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.1
  - pip:
      - azureml-defaults
      - mlflow
      - azureml-mlflow
      - ray-on-aml==0.0.8
      - torch
      - torchvision==0.8.1
  - matplotlib
  - pip
name: azureml_cfc9e96c7b0b43301a0ba4c6bd3548e5
